services:
  meilisearch:
    image: getmeili/meilisearch:v1
    # ports:
    # - "7700:7700"
    environment:
      - MEILI_MASTER_KEY
    volumes:
      - ./meili_data:/meili_data

  backend:
    depends_on:
      - meilisearch
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY
      - BIND_URL=0.0.0.0:3000

  frontend:
    depends_on:
      - backend
    build:
      context: frontend
    environment:
      ORIGIN: https://contratopublico.chicoferreira.dev
      BACKEND_URL: http://backend:3000
