listen_port = 80

max_clients = 10000
max_concurrent_streams = 10000

[apps.contratopublico]
server_name = 'contratopublico.pt'

[[apps.contratopublico.reverse_proxy]]
upstream = [{ location = 'frontend:3000' }]
upstream_options = ["keep_original_host"]

[[apps.contratopublico.reverse_proxy]]
path = '/api'
upstream = [{ location = 'backend:3000' }]
