name: contratopublico

include: [compose.yml]
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN
    command: "tunnel run"
    depends_on:
      - frontend
    restart: unless-stopped
