name: contratopublico-dev

services:
  meilisearch:
    image: getmeili/meilisearch:v1
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - ../data/meili_data:/meili_data
