name: contratopublico

services:
  meilisearch:
    restart: unless-stopped
    image: getmeili/meilisearch:v1
    # ports:
    # - "7700:7700"
    environment:
      - MEILI_MASTER_KEY
      - MEILI_EXPERIMENTAL_SEARCH_QUEUE_SIZE=3000
      - MEILI_LOG_LEVEL=WARN
    volumes:
      - ../backend/data/meili_data:/meili_data

  backend:
    restart: unless-stopped
    depends_on:
      - meilisearch
    build:
      context: ../backend
    volumes:
      - ../backend/data/scraper:/data/scraper
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY
      - BIND_URL=0.0.0.0:3000
      - RUST_LOG=info
      - SAVED_PAGES_PATH=/data/scraper/saved_pages.json
      - SCRAPER_INTERVAL_SECS=1800 # 30 minutes

  frontend:
    restart: unless-stopped
    depends_on:
      - backend
    build:
      context: ../frontend
    environment:
      ORIGIN: https://contratopublico.pt
      BACKEND_URL: http://backend:3000

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../monitoring/prometheus/data:/prometheus:rw
    depends_on:
      - backend
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ../monitoring/grafana:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped

  rpxy:
    image: jqtype/rpxy:latest
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    depends_on:
      - frontend
      - backend
    environment:
      - LOG_LEVEL=warn
    volumes:
      # - ../rpxy/log:/rpxy/log:rw
      # - ../rpxy/cache:/rpxy/cache:rw
      # - ../rpxy/acme_registry:/rpxy/acme_registry:rw
      - ../rpxy/config/config.toml:/etc/rpxy.toml:ro
