name: contratopublico

services:
  meilisearch:
    image: getmeili/meilisearch:v1
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - ./meili_data:/meili_data
