{
 "title": "Backend API Metrics",
 "tags": [
  "backend",
  "api",
  "metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total requests in the last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency Backend",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_requests_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}